### ISSUE TITLE
Manual version stops after preloading page 1

### ISSUE THREAD

**Issue by kleinerPanzer** [apankowski/doc88-downloader#19] opened 2024-11-20 06:20 UTC
**Bug description**
When using manual option (pasting JS into console) and attempting to download pages, the script stops running after preloading the first page.

**Reproduction steps**
1. Instructions followed as Option B described up until requesting 'downloadPages()'
2. 'downloadPages()' entered

**Expected behavior**
Pages would download in a zip folder.

**Environment**
 - Tool version: fc49b53cb18fd6ddf0c3f81bec9c6b58f5551f06 (version available as of 2024-11-19)
 - Browser version: Opera GX LVL 6 (core: 114.0.5282.159)
 - OS version: Windows 11
 - Link to doc88 document https://www.doc88.com/p-08739245924160.html
 - Output in Developer Console 
![image](https://github.com/user-attachments/assets/8d91a4f5-2772-421e-ac0a-47ab5e2925d5)

**Additional context**
Same result occurred with a few other parameters tried within 'downloadPages()'

**Comment by apankowski** [comment] 2024-11-24 10:56
Thank you for the detailed report, that's very helpful.

Unfortunately I cannot reproduce it on my end.

Installed fresh Opera GX on Windows 11, pasted the code and run `downloadPages()`. Everything worked as expected.
Did the same with classic Opera - again, no problems.
Tried repeating this a couple of times - again, without problems.

Screenshots:

![image](https://github.com/user-attachments/assets/0170e353-571c-4824-a5ae-02ca6acf3cb5)

![image](https://github.com/user-attachments/assets/756b7d98-f9eb-4493-85ae-13eab1ab18cb)

Couple potential things that come to mind:

1. Have you tried repeating the process? Does the it always fail for this page?
2. Have you tried other doc88 documents? Does it also repeatedly fail?
3. Do you have any browser extensions or apps that modify or interact with the DOM? Thinks like: AdBlock, 1password browser extension, antivirus browser integration, etc.
4. Do you have an unreliable internet connection?

**Comment by apankowski** [comment] 2024-12-11 19:03
@kleinerPanzer issues #19, #21 and #22 all seem to be related to a new protection mechanism (captcha) that doc88 introduced.

I've added handling of captcha in #23 and merged.

Could you try again with the new bookmark / code that's in the repo's default branch?

You'll still have to solve the captcha, but after solving it the download process should progress.

**Comment by apankowski** [comment] 2024-12-24 15:21
I'm gonna assume this has been resolved 🤞

**Closed by apankowski** 2024-12-24 15:21 UTC
Labels: bug
