### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Untittledmiss** [apankowski/doc88-downloader#21] opened 2024-11-28 21:19 UTC
**Bug description - actual behavior**

When clicking the bookmark the download does not start and the file moves to the first page but not contunue. it remains static.

**Expected behavior**

It should start downloading the pages as gpg.

**Comment by apankowski** [comment] 2024-11-29 09:43
@Untittledmiss please provide more context. See bug temple. The information you have provided so far if not sufficient to debug the issue.

**Comment by DarkRoku12** [comment] 2024-11-30 02:08
Actually, it does still work, the issue is the following:

There is a captcha one must resolve first to gain access to the following pages.
![image](https://github.com/user-attachments/assets/10812077-7e84-4459-ad1a-b1a77efaad1b)

If not, the script (I'm using the manual, console version), will complain about not being able to find the page #2.
![image](https://github.com/user-attachments/assets/a4325c0b-1b56-404b-ac6a-caee66a1c03e)

After solving the captcha and gaining access to the remaining pages, the script worked just as good.
![image](https://github.com/user-attachments/assets/f9810fb3-b1ee-480b-8d1b-c5b7127bfec1)

**Comment by Untittledmiss** [comment] 2024-11-30 16:48
I ACTUALLY DID THAT IN THE BOOKMARK FORMAT, ALL THE PAGES ARE VISIBLE BUT AS I SAID IN THE "BUG DESCRIPTION" WHEN clicking the bookmark IT DOES NOT WORK I DON'T KNOW THAT BROWSER DO YOU USE BUT MICROSOFT BING DOES NOT WORK

**Comment by Untittledmiss** [comment] 2024-11-30 16:48
PLEASE READ ALL THE BUG DESCRIPTION BEFORE COMENTING, THANK YOU

**Comment by Untittledmiss** [comment] 2024-12-04 15:26
I tried to use the manual format, but i get no response. 
![2024-12-04 092519](https://github.com/user-attachments/assets/d2a3edf3-4686-463c-9a97-b86393823d2f)

**Comment by apankowski** [comment] 2024-12-11 19:05
@DarkRoku12 thanks for spotting this! Not sure why but captcha didn't appear on most of my devices.

@Untittledmiss issues #19, #21 and #22 all seem to be related to captcha that doc88 introduced.

I've added handling of captcha in #23 and merged.
You'll still have to solve the captcha, but after solving it the download process should progress.
Please try again with the new bookmark / code that's in the repo's default branch and report if it's working.

**Closed** 2024-12-11 19:30 UTC
Labels: bug
